.l main:
    .mov byte(9), byte(0)
    .mov byte(9), byte(0)
    .mov byte(9), byte(0)
    .mov byte(9), byte(0)
    .mov byte(9), byte(0)
    .mov byte(9), byte(0)
    .mov byte(9), byte(0)
    .mov byte(9), byte(0)
    .mov byte(9), byte(0)
    .mov byte(9), byte(0)
    .mov byte(9), byte(0)
    .mov byte(9), byte(0)
